-- 코드를 입력하세요
SELECT o.AUTHOR_ID, j.AUTHOR_NAME, o.CATEGORY, o.TOTAL_SALES
FROM (SELECT b.AUTHOR_ID, b.CATEGORY, SUM(s.SALES * b.PRICE)  AS TOTAL_SALES
    FROM BOOK b
    JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
    WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY b.CATEGORY, b.AUTHOR_ID) o
JOIN AUTHOR j
ON o.AUTHOR_ID = j.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC