-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT i.ITEM_ID
    FROM ITEM_TREE i
    LEFT JOIN ITEM_TREE j
    ON i.ITEM_ID = j.PARENT_ITEM_ID
    WHERE j.ITEM_ID IS NULL)
ORDER BY ITEM_ID DESC;