-- 코드를 입력하세요

-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문을 작성



# SELECT o.CAR_ID, o.CAR_TYPE, ROUND(o.DAILY_FEE * 30 * (1 - 0.01 * j.DISCOUNT_RATE), 0) AS FEE
# FROM (SELECT h.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
#     LEFT JOIN CAR_RENTAL_COMPANY_CAR c
#     ON h.CAR_ID = c.CAR_ID
#     WHERE TIMESTAMPDIFF(day, h.START_DATE, '2022-11-30') < 0 OR TIMESTAMPDIFF(day, h.END_DATE, '2022-11-01') > 0
#     GROUP BY h.CAR_ID) o
# LEFT JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     WHERE DURATION_TYPE = '30일 이상') j
# ON o.CAR_TYPE = j.CAR_TYPE
# WHERE ROUND(o.DAILY_FEE * 30 * (1 - 0.01 * j.DISCOUNT_RATE), 0) >= 500000 AND ROUND(o.DAILY_FEE * 30 * (1 - 0.01 * j.DISCOUNT_RATE), 0)<2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# SELECT h.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
#     LEFT JOIN CAR_RENTAL_COMPANY_CAR c
#     ON h.CAR_ID = c.CAR_ID
#     WHERE TIMESTAMPDIFF(day, h.START_DATE, '2022-11-30') < 0 OR TIMESTAMPDIFF(day, h.END_DATE, '2022-11-01') > 0
#     GROUP BY h.CAR_ID;



SELECT o.CAR_ID, o.CAR_TYPE, ROUND(o.DAILY_FEE * (1 - 0.01 * j.DISCOUNT_RATE) * 30, 0) AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN (SELECT DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE TIMESTAMPDIFF(day, h.START_DATE, '2022-11-30') >= 0 AND TIMESTAMPDIFF(day, h.END_DATE, '2022-11-01') <= 0)) o
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상') j
ON o.CAR_TYPE = j.CAR_TYPE
WHERE ROUND(o.DAILY_FEE * (1 - 0.01 * j.DISCOUNT_RATE) * 30, 0)>= 500000 AND ROUND(o.DAILY_FEE * (1 - 0.01 * j.DISCOUNT_RATE) * 30, 0)< 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

