-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, CONCAT(CITY, " ", u.STREET_ADDRESS1, " ", u.STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER u
JOIN (SELECT WRITER_ID, COUNT(*) AS COUNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT >= 3) b
ON u.USER_ID = b.WRITER_ID
ORDER BY USER_ID DESC;