-- 코드를 입력하세요
SELECT j.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM FROM FIRST_HALF GROUP BY FLAVOR) f
RIGHT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM FROM JULY GROUP BY FLAVOR) j
ON f.FLAVOR = j.FLAVOR
ORDER BY j.SUM + f.SUM DESC
LIMIT 3;