--  2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL문을 작성
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 항목이 출력

SELECT o.APNT_NO, p.PT_NAME, p.PT_NO, o.MCDP_CD, o.DR_NAME, o.APNT_YMD
    FROM (SELECT o.APNT_NO, o.PT_NO, d.MCDP_CD, d.DR_NAME, o.APNT_YMD
    FROM (SELECT APNT_NO, PT_NO, MDDR_ID, APNT_YMD
        FROM APPOINTMENT
        WHERE TIMESTAMPDIFF(day, DATE_FORMAT(APNT_YMD, '%Y-%m-%d'), '2022-04-13') = 0 AND TIMESTAMPDIFF(day, DATE_FORMAT(IFNULL(APNT_CNCL_YMD, '2022-04-14'), '%Y-%m-%d'), '2022-04-13') <= 0 AND MCDP_CD = 'CS') o
    JOIN DOCTOR d
    ON o.MDDR_ID = d.DR_ID) o
JOIN PATIENT p
ON p.PT_NO = o.PT_NO
ORDER BY APNT_YMD;
































-- 코드를 입력하세요
# SELECT j.APNT_NO, j.PT_NAME, j.PT_NO, j.MCDP_CD, d.DR_NAME, j.APNT_YMD
# FROM DOCTOR d
# JOIN (SELECT j.APNT_NO, p.PT_NAME, j.PT_NO, j.MCDP_CD, j.MDDR_ID, j.APNT_YMD
# FROM PATIENT p 
# JOIN (SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
# FROM APPOINTMENT
# WHERE (APNT_CNCL_YN ='N' OR APNT_CNCL_YMD > '2022-04-13') AND MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04%') j
# ON p.PT_NO = j.PT_NO
# ) j
# ON d.DR_ID = j.MDDR_ID
# ORDER BY APNT_YMD