-- 코드를 입력하세요
SELECT j.APNT_NO, j.PT_NAME, j.PT_NO, j.MCDP_CD, d.DR_NAME, j.APNT_YMD
FROM DOCTOR d
JOIN (SELECT j.APNT_NO, p.PT_NAME, j.PT_NO, j.MCDP_CD, j.MDDR_ID, j.APNT_YMD
FROM PATIENT p 
JOIN (SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
FROM APPOINTMENT
WHERE (APNT_CNCL_YN ='N' OR APNT_CNCL_YMD > '2022-04-13') AND MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04%') j
ON p.PT_NO = j.PT_NO
) j
ON d.DR_ID = j.MDDR_ID
ORDER BY APNT_YMD

