-- 코드를 작성해주세요
SELECT e.ID, e.GENOTYPE, p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA e
INNER JOIN (SELECT ID, GENOTYPE FROM ECOLI_DATA) p
ON e.PARENT_ID = p.ID
WHERE p.GENOTYPE & e.GENOTYPE = p.GENOTYPE
ORDER BY ID;