SELECT YEAR(o.DIFFERENTIATION_DATE) as YEAR, (t.MAX_COLONY - o.SIZE_OF_COLONY) AS YEAR_DEV, o.ID
FROM ECOLI_DATA o
INNER JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) t
ON YEAR(o.DIFFERENTIATION_DATE) = t.YEAR
ORDER BY YEAR, YEAR_DEV;
