-- 코드를 작성해주세요
SELECT n.YEAR, (n.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV, e.ID
FROM ECOLI_DATA e
INNER JOIN (SELECT MAX(SIZE_OF_COLONY) as MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR FROM ECOLI_DATA GROUP BY YEAR) n
ON YEAR(e.DIFFERENTIATION_DATE) = n.YEAR
ORDER BY YEAR, YEAR_DEV;