-- 코드를 입력하세요
SELECT f.CATEGORY, f.PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) j
ON f.CATEGORY = j.CATEGORY
WHERE f.PRICE = j.MAX_PRICE
ORDER BY PRICE DESC;