-- 코드를 작성해주세요
SELECT j.CNT AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, j.FISH_TYPE
FROM FISH_INFO f
JOIN (SELECT FISH_TYPE, COUNT(ID) AS CNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH, 10)) >= 33) j
ON f.FISH_TYPE = j.FISH_TYPE
GROUP BY j.FISH_TYPE
ORDER BY j.FISH_TYPE;