-- 코드를 작성해주세요
-- DEVELOPERS 테이블에서 GRADE별 개발자의 정보를 조회하려 합니다. GRADE는 다음과 같이 정해집니다.

# A : Front End 스킬과 Python 스킬을 함께 가지고 있는 개발자
# B : C# 스킬을 가진 개발자
# C : 그 외의 Front End 개발자
# GRADE가 존재하는 개발자의 GRADE, ID, EMAIL을 조회하는 SQL 문

WITH FRONT_END_ID AS (
    SELECT ID 
    FROM DEVELOPERS d
    JOIN SKILLCODES s
    ON d.SKILL_CODE & s.CODE = s.CODE
    WHERE s.CATEGORY = 'Front End'
), PYTHON_ID AS (
    SELECT ID 
    FROM DEVELOPERS d
    JOIN SKILLCODES s
    ON d.SKILL_CODE & s.CODE = s.CODE
    WHERE s.NAME = 'Python'
), C_SHARP_ID AS (
    SELECT ID 
    FROM DEVELOPERS d
    JOIN SKILLCODES s
    ON d.SKILL_CODE & s.CODE = s.CODE
    WHERE s.NAME = 'C#'
)
SELECT o.GRADE, o.ID, o.EMAIL
FROM (SELECT 
    CASE
        WHEN ID IN (SELECT ID FROM FRONT_END_ID) AND ID IN (SELECT ID FROM PYTHON_ID) THEN 'A'
        WHEN ID IN (SELECT ID FROM C_SHARP_ID) THEN 'B'
        WHEN ID IN (SELECT ID FROM FRONT_END_ID) THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS) o
WHERE o.GRADE IS NOT NULL
ORDER BY o.GRADE, o.ID;
